class TaskNotFoundError(Exception):
    pass


class TaskAlreadyExistsError(Exception):
    pass
